// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuRbaNeGTzNLJ7_wyc3t1GnD2QeAhEa_8',
    appId: '1:16916994820:web:d028663c4d7dd12ae60e51',
    messagingSenderId: '16916994820',
    projectId: 'fire-messenger-b02a1',
    authDomain: 'fire-messenger-b02a1.firebaseapp.com',
    storageBucket: 'fire-messenger-b02a1.appspot.com',
    measurementId: 'G-76TNH733PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASnrZDqK8ge7Tciu0KTRYKpBdUJMMddOU',
    appId: '1:16916994820:android:74409187039737abe60e51',
    messagingSenderId: '16916994820',
    projectId: 'fire-messenger-b02a1',
    storageBucket: 'fire-messenger-b02a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ7XnsBgR1HW1KXejSraQQbzSlUsUvEaA',
    appId: '1:16916994820:ios:197e75eff4bece5fe60e51',
    messagingSenderId: '16916994820',
    projectId: 'fire-messenger-b02a1',
    storageBucket: 'fire-messenger-b02a1.appspot.com',
    iosClientId: '16916994820-37d5bbuehpniisf2u6357r3l7mn2i5b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ7XnsBgR1HW1KXejSraQQbzSlUsUvEaA',
    appId: '1:16916994820:ios:925f4337af97256ae60e51',
    messagingSenderId: '16916994820',
    projectId: 'fire-messenger-b02a1',
    storageBucket: 'fire-messenger-b02a1.appspot.com',
    iosClientId: '16916994820-0mbkuf1ctbo53485ho1vh26p6dn1e4gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireMessenger.RunnerTests',
  );
}
